#Tratamento das Planilhas de Registro de Vendas

In [20]:
import pandas as pd
from src.limpeza import limpar_preco

In [21]:
vendas22 = pd.read_excel("../raw/Base Vendas - 2022.xlsx")
vendas23 = pd.read_excel("../raw/Base Vendas - 2023.xlsx")
vendas24 = pd.read_excel("../raw/Base Vendas - 2024.xlsx")

##2022

In [22]:
vendas22.info()

<class 'pandas.DataFrame'>
RangeIndex: 371102 entries, 0 to 371101
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Data Venda      371102 non-null  datetime64[us]
 1   Id Loja         371102 non-null  int64
 2   Id Produto      371102 non-null  int64
 3   Id Cliente      371102 non-null  int64
 4   Qtd. Vendida    371102 non-null  int64
 5   Qtd. Devolvida  371102 non-null  int64
 6   Preco Unitario  371102 non-null  str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 19.8 MB

In [23]:
vendas22.head()

,Data Venda,Id Loja,Id Produto,Id Cliente,Qtd. Vendida,Qtd. Devolvida,Preco Unitario
0,2022-01-01,500,83,7604,1,0,99.99
1,2022-01-01,879,83,7605,2,0,99.99
2,2022-01-01,679,83,7606,1,0,99.99
3,2022-01-01,791,83,7607,1,0,99.99
4,2022-01-01,644,83,7608,4,0,99.99

In [24]:
vendas22 = limpar_preco(vendas22, "Preco Unitario")

In [25]:
vendas22.rename(columns={"Preco Unitario":"Preço Unitário"}, inplace=True)

In [26]:
vendas22.info()

<class 'pandas.DataFrame'>
RangeIndex: 371102 entries, 0 to 371101
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Data Venda      371102 non-null  datetime64[us]
 1   Id Loja         371102 non-null  int64
 2   Id Produto      371102 non-null  int64
 3   Id Cliente      371102 non-null  int64
 4   Qtd. Vendida    371102 non-null  int64
 5   Qtd. Devolvida  371102 non-null  int64
 6   Preço Unitário  371102 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(5)
memory usage: 19.8 MB

In [27]:
vendas22.describe()

,Data Venda,Id Loja,Id Produto,Id Cliente,Qtd. Vendida,Qtd. Devolvida,Preço Unitário
count,371102,371102.000000,371102.000000,371102.000000,371102.000000,371102.000000,371102.000000
mean,2022-07-01 12:34:23.251612,690.820413,1589.441997,9311.347409,1.000046,0.005629,180.198455
min,2022-01-01 00:00:00,423.000000,1.000000,1.000000,1.000000,0.000000,4.980000
25%,2022-04-02 00:00:00,559.000000,1676.000000,4629.000000,1.000000,0.000000,6.990000
50%,2022-07-03 00:00:00,693.000000,1706.000000,9474.000000,1.000000,0.000000,32.000000
75%,2022-09-28 00:00:00,823.000000,1768.000000,14101.750000,1.000000,0.000000,70.130000
max,2022-12-31 00:00:00,952.000000,2512.000000,18484.000000,4.000000,1.000000,3199.990000
std,NaN,152.245359,476.687505,5383.712244,0.009711,0.074816,480.766103

##2023

In [28]:
vendas23.info()

<class 'pandas.DataFrame'>
RangeIndex: 379451 entries, 0 to 379450
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Data Venda      379451 non-null  datetime64[us]
 1   Id Loja         379451 non-null  int64
 2   Id Produto      379451 non-null  int64
 3   Id Cliente      379451 non-null  int64
 4   Qtd. Vendida    379451 non-null  int64
 5   Qtd. Devolvida  379451 non-null  int64
 6   Preco Unitario  379451 non-null  str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 20.3 MB

In [29]:
vendas23.head()

,Data Venda,Id Loja,Id Produto,Id Cliente,Qtd. Vendida,Qtd. Devolvida,Preco Unitario
0,2023-01-01,649,1701,333,2,0,4.98
1,2023-01-01,901,1701,336,3,0,4.98
2,2023-01-01,844,1701,338,5,0,4.98
3,2023-01-01,471,1701,340,3,0,4.98
4,2023-01-01,732,1701,341,4,0,4.98

In [30]:
vendas23 = limpar_preco(vendas23, "Preco Unitario")
vendas23.rename(columns={"Preco Unitario":"Preço Unitário"}, inplace=True)

In [31]:
vendas23.info()

<class 'pandas.DataFrame'>
RangeIndex: 379451 entries, 0 to 379450
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Data Venda      379451 non-null  datetime64[us]
 1   Id Loja         379451 non-null  int64
 2   Id Produto      379451 non-null  int64
 3   Id Cliente      379451 non-null  int64
 4   Qtd. Vendida    379451 non-null  int64
 5   Qtd. Devolvida  379451 non-null  int64
 6   Preço Unitário  379451 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(5)
memory usage: 20.3 MB

In [32]:
vendas23.describe()

,Data Venda,Id Loja,Id Produto,Id Cliente,Qtd. Vendida,Qtd. Devolvida,Preço Unitário
count,379451,379451.000000,379451.000000,379451.000000,379451.000000,379451.000000,379451.000000
mean,2023-06-15 08:24:35.554946,691.058759,1073.599063,8902.296995,2.254125,0.006082,289.156250
min,2023-01-01 00:00:00,423.000000,1.000000,2.000000,1.000000,0.000000,4.980000
25%,2023-03-14 00:00:00,560.000000,176.000000,4173.000000,1.000000,0.000000,25.000000
50%,2023-06-06 00:00:00,693.000000,1296.000000,8719.000000,1.000000,0.000000,126.900000
75%,2023-09-12 00:00:00,823.000000,1698.000000,13528.000000,4.000000,0.000000,399.000000
max,2023-12-31 00:00:00,952.000000,2348.000000,18484.000000,6.000000,1.000000,2652.900000
std,NaN,152.135221,713.856641,5342.275352,1.738972,0.077753,459.629067

##2024

In [33]:
vendas24.info()

<class 'pandas.DataFrame'>
RangeIndex: 395408 entries, 0 to 395407
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Data Venda      395408 non-null  datetime64[us]
 1   Id Loja         395408 non-null  int64
 2   Id Produto      395408 non-null  int64
 3   Id Cliente      395408 non-null  int64
 4   Qtd. Vendida    395408 non-null  int64
 5   Qtd. Devolvida  395408 non-null  int64
 6   Preco Unitario  395408 non-null  str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 21.1 MB

In [34]:
vendas24.head()

,Data Venda,Id Loja,Id Produto,Id Cliente,Qtd. Vendida,Qtd. Devolvida,Preco Unitario
0,2024-01-01,759,206,17311,1,0,569.00
1,2024-01-01,856,206,17312,2,0,569.00
2,2024-01-01,741,206,17314,1,0,569.00
3,2024-01-01,476,206,17315,1,0,569.00
4,2024-01-01,740,206,17316,5,0,569.00

In [35]:
vendas24 = limpar_preco(vendas24, "Preco Unitario")
vendas24.rename(columns={"Preco Unitario":"Preço Unitário"}, inplace=True)

In [36]:
vendas24.info()

<class 'pandas.DataFrame'>
RangeIndex: 395408 entries, 0 to 395407
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Data Venda      395408 non-null  datetime64[us]
 1   Id Loja         395408 non-null  int64
 2   Id Produto      395408 non-null  int64
 3   Id Cliente      395408 non-null  int64
 4   Qtd. Vendida    395408 non-null  int64
 5   Qtd. Devolvida  395408 non-null  int64
 6   Preço Unitário  395408 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(5)
memory usage: 21.1 MB

In [37]:
vendas24.describe()

,Data Venda,Id Loja,Id Produto,Id Cliente,Qtd. Vendida,Qtd. Devolvida,Preço Unitário
count,395408,395408.000000,395408.000000,395408.000000,395408.000000,395408.000000,395408.000000
mean,2024-06-17 18:29:03.042123,691.325112,1478.290437,9575.032913,2.252911,0.007956,273.620997
min,2024-01-01 00:00:00,423.000000,16.000000,2.000000,1.000000,0.000000,4.980000
25%,2024-03-28 00:00:00,560.000000,1667.000000,5181.000000,1.000000,0.000000,8.880000
50%,2024-06-11 00:00:00,693.000000,1695.000000,9754.000000,1.000000,0.000000,32.000000
75%,2024-09-03 00:00:00,823.000000,1770.000000,14146.000000,4.000000,0.000000,179.000000
max,2024-12-30 00:00:00,952.000000,2479.000000,18484.000000,6.000000,1.000000,2652.900000
std,NaN,152.325266,577.551911,5284.137874,1.740057,0.088843,547.371965

In [38]:
vendas22.to_excel("../processed/vendas22.xlsx", index=False)
vendas23.to_excel("../processed/vendas23.xlsx", index=False)
vendas24.to_excel("../processed/vendas24.xlsx", index=False)