# Integração das Tabelas

In [1]:
import pandas as pd

In [2]:
vendas22 = pd.read_excel("../processed/vendas22.xlsx")
vendas23 = pd.read_excel("../processed/vendas23.xlsx")
vendas24 = pd.read_excel("../processed/vendas24.xlsx")

In [3]:
df_vendas = pd.concat(
    [vendas22,vendas23,vendas24],
    ignore_index=True
)

In [4]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1145961 entries, 0 to 1145960
Data columns (total 7 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   Data Venda      1145961 non-null  datetime64[us]
 1   Id Loja         1145961 non-null  int64
 2   Id Produto      1145961 non-null  int64
 3   Id Cliente      1145961 non-null  int64
 4   Qtd. Vendida    1145961 non-null  int64
 5   Qtd. Devolvida  1145961 non-null  int64
 6   Preço Unitário  1145961 non-null  float64
dtypes: datetime64[us](1), float64(1), int64(5)
memory usage: 61.2 MB

In [5]:
df_vendas.head()

,Data Venda,Id Loja,Id Produto,Id Cliente,Qtd. Vendida,Qtd. Devolvida,Preço Unitário
0,2022-01-01,500,83,7604,1,0,99.99
1,2022-01-01,879,83,7605,2,0,99.99
2,2022-01-01,679,83,7606,1,0,99.99
3,2022-01-01,791,83,7607,1,0,99.99
4,2022-01-01,644,83,7608,4,0,99.99

In [6]:
clientes = pd.read_excel("../processed/clientes.xlsx")
lojas = pd.read_excel("../processed/lojas.xlsx")
produtos = pd.read_excel("../processed/produtos.xlsx")

In [7]:
df_vendas = df_vendas.merge(
    clientes,
    how="left",
    on="Id Cliente"
)

In [8]:
df_vendas.head()

,Data Venda,Id Loja,Id Produto,Id Cliente,Qtd. Vendida,Qtd. Devolvida,Preço Unitário,Nome Completo,Gênero,Data de Nascimento,Nome Cliente
0,2022-01-01,500,83,7604,1,0,99.99,Evyne J.,Feminino,1989-03-11,Evyne
1,2022-01-01,879,83,7605,2,0,99.99,Polliana P.,Feminino,1989-05-21,Polliana
2,2022-01-01,679,83,7606,1,0,99.99,Elivelto H.,Masculino,1989-11-15,Elivelto
3,2022-01-01,791,83,7607,1,0,99.99,Elisangela G.,Feminino,1989-10-24,Elisangela
4,2022-01-01,644,83,7608,4,0,99.99,Philippe J.,Masculino,1989-06-12,Philippe

In [9]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1145961 entries, 0 to 1145960
Data columns (total 11 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   Data Venda          1145961 non-null  datetime64[us]
 1   Id Loja             1145961 non-null  int64
 2   Id Produto          1145961 non-null  int64
 3   Id Cliente          1145961 non-null  int64
 4   Qtd. Vendida        1145961 non-null  int64
 5   Qtd. Devolvida      1145961 non-null  int64
 6   Preço Unitário      1145961 non-null  float64
 7   Nome Completo       1145961 non-null  str
 8   Gênero              1145961 non-null  str
 9   Data de Nascimento  1145961 non-null  datetime64[us]
 10  Nome Cliente        1145961 non-null  str
dtypes: datetime64[us](2), float64(1), int64(5), str(3)
memory usage: 124.0 MB

In [10]:
df_vendas = df_vendas.merge(
    lojas,
    how="left",
    on="Id Loja"
)

In [11]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1145961 entries, 0 to 1145960
Data columns (total 16 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   Data Venda          1145961 non-null  datetime64[us]
 1   Id Loja             1145961 non-null  int64
 2   Id Produto          1145961 non-null  int64
 3   Id Cliente          1145961 non-null  int64
 4   Qtd. Vendida        1145961 non-null  int64
 5   Qtd. Devolvida      1145961 non-null  int64
 6   Preço Unitário      1145961 non-null  float64
 7   Nome Completo       1145961 non-null  str
 8   Gênero              1145961 non-null  str
 9   Data de Nascimento  1145961 non-null  datetime64[us]
 10  Nome Cliente        1145961 non-null  str
 11  Localidade          1145961 non-null  str
 12  Cidade              1145961 non-null  str
 13  Tipo Loja           1145961 non-null  str
 14  Nome Gerente        1145961 non-null  str
 15  Sobrenome Gerente   1145961 non-null  str
dtypes: datetime64[us](2), float64(1), int64(5), str(8)
memory usage: 228.2 MB

In [12]:
df_vendas.head()

,Data Venda,Id Loja,Id Produto,Id Cliente,Qtd. Vendida,Qtd. Devolvida,Preço Unitário,Nome Completo,Gênero,Data de Nascimento,Nome Cliente,Localidade,Cidade,Tipo Loja,Nome Gerente,Sobrenome Gerente
0,2022-01-01,500,83,7604,1,0,99.99,Evyne J.,Feminino,1989-03-11,Evyne,Estados Unidos - América do Norte,Lebanon,Física,Francisco,Sousa
1,2022-01-01,879,83,7605,2,0,99.99,Polliana P.,Feminino,1989-05-21,Polliana,Estados Unidos - América do Norte,Minden,Física,Pedro,Gomes
2,2022-01-01,679,83,7606,1,0,99.99,Elivelto H.,Masculino,1989-11-15,Elivelto,Austrália - Austrália,Rhodes,Física,Marcos,Barbosa
3,2022-01-01,791,83,7607,1,0,99.99,Elisangela G.,Feminino,1989-10-24,Elisangela,Estados Unidos - América do Norte,Austin,Física,Maria,Silva
4,2022-01-01,644,83,7608,4,0,99.99,Philippe J.,Masculino,1989-06-12,Philippe,Estados Unidos - América do Norte,Lake Oswego,Física,Carlos,Martins

In [13]:
df_vendas = df_vendas.merge(
    produtos.drop(columns="Preço Unitário"),
    how="left",
    on="Id Produto"
)

In [14]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1145961 entries, 0 to 1145960
Data columns (total 20 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   Data Venda          1145961 non-null  datetime64[us]
 1   Id Loja             1145961 non-null  int64
 2   Id Produto          1145961 non-null  int64
 3   Id Cliente          1145961 non-null  int64
 4   Qtd. Vendida        1145961 non-null  int64
 5   Qtd. Devolvida      1145961 non-null  int64
 6   Preço Unitário      1145961 non-null  float64
 7   Nome Completo       1145961 non-null  str
 8   Gênero              1145961 non-null  str
 9   Data de Nascimento  1145961 non-null  datetime64[us]
 10  Nome Cliente        1145961 non-null  str
 11  Localidade          1145961 non-null  str
 12  Cidade              1145961 non-null  str
 13  Tipo Loja           1145961 non-null  str
 14  Nome Gerente        1145961 non-null  str
 15  Sobrenome Gerente   1145961 non-null  str
 16  Nome Produto        1145961 non-null  str
 17  Categoria           1145961 non-null  str
 18  Marca               1145961 non-null  str
 19  Custo Unitário      1145961 non-null  float64
dtypes: datetime64[us](2), float64(2), int64(5), str(11)
memory usage: 330.8 MB

In [3]:
df_vendas["Marca"] = df_vendas["Marca"].str.strip()

In [4]:
df_vendas.to_parquet("../processed/df_Vendas.parquet", index=False)